repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.1
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  # We use a custom shellcheck pre-commit hook that does not require a running Docker daemon.
  # See https://github.com/koalaman/shellcheck/issues/2495
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
