# Minimal configuration example
# Only required fields are shown

compaction_strategy: bentley_saxe:no_rebuild

levels:
  model:
    layers:
      - size: 128
      - size: 64
    train_params:
      threshold_samples: 1000
      batch_size: 256
      epochs: 3
      max_iters: 10
      retrain_strategy: no_retrain
  bucket_size: 1000

buffer_size: 1000
input_shape: 128
arity: 2
device:
  cpu
distance_fn: l2
delete_method: oid_to_bucket
