device: cpu
input_shape: 768
label_method:
  type: knn
  value:
    max_iters: 10 
arity: 3
levelling: bentley_saxe
buffer_size: 40
levels:
  0:
    model:
      layers:
      - type: linear
        value: 256
      - type: relu
      - type: linear
        value: 256
      - type: relu
      train_params:
        epochs: 3
        batch_size: 8
        threshold_samples: 100
        label_method:
          type: knn
          value:
            max_iters: 0
    bucket_size: 30

