device: cpu
input_shape: 768
label_method:
  type: knn
  value:
    max_iters: 10 
arity: 3
levelling: bentley_saxe
buffer_size: 40
levels:
  0:
    model:
      layers:
      - type: Linear
        value: 256
      - type: ReLU
      - type: Linear
        value: 256
      - type: ReLU
    bucket_size: 30


