levelling: bentley_saxe
levels:
  0:
    model:
      layers:
      - type: linear
        value: 128
      - type: relu
      train_params:
        threshold_samples: 5000
        batch_size: 256
        epochs: 10
        max_iters: 10
      retrain_params:
        threshold_samples: 5000
        batch_size: 256
        epochs: 10
        max_iters: 10
    bucket_size: 200
buffer_size: 200
input_shape: 768
arity: 3
device: cpu
distance_fn: dot