levelling: bentley_saxe
levels:
  0:
    model:
      layers:
      - type: linear
        value: 256
      - type: relu
      train_params:
        threshold_samples: 100000
        batch_size: 8
        epochs: 10
        max_iters: 10
      retrain_params:
        threshold_samples: 100000
        batch_size: 8
        epochs: 10
        max_iters: 10
    bucket_size: 5000
buffer_size: 5000
input_shape: 768
arity: 3
device: cpu
distance_fn: l2